import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';
import ts from 'typescript';
const state={user:'owner',calls:[],missing:false,conflict:false};globalThis.__pfAccountsTest=state;
const compile=async file=>ts.transpileModule(await readFile(new URL(file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const url=code=>`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`;
const base=code=>code.replace(/import \{ NextResponse \} from "next\/server";/,'const NextResponse={json:(data,options)=>Response.json(data,options)};').replace(/import \{ currentUserId \} from "[^\"]+";/,'const currentUserId=async()=>globalThis.__pfAccountsTest.user;');
let code=base(await compile('../app/api/accounts/route.ts')).replace(/import \{[^}]+\} from "[^\"]+accounts-db";/,`const listAccounts=async user=>[{id:'account',broker:'증권사',name:'ISA'}];const createAccount=async(user,broker,name)=>{globalThis.__pfAccountsTest.calls.push({user,broker,name});return {id:'account',broker,name};};const updateAccount=async(user,id,broker,name)=>{const s=globalThis.__pfAccountsTest;s.calls.push({user,id,broker,name});if(s.conflict)throw {code:'23505'};return s.missing?null:{accounts:[]};};`).replace(/import \{ listHoldings \} from "[^\"]+holdings-db";/,'const listHoldings=async()=>[];');
const accounts=await import(url(code));
code=base(await compile('../app/api/holdings/route.ts')).replace(/import \{[^}]+\} from "[^\"]+holdings-db";/,`const listHoldings=async()=>[],removeHolding=async()=>[],updateHoldingAmounts=async()=>[],updateHoldingInstrument=async()=>[],updateHoldingAssignment=async()=>{};
const moveHoldingAccount=async(user,id,accountId)=>{const s=globalThis.__pfAccountsTest;s.calls.push({user,id,accountId});if(s.missing)throw new Error('계좌를 찾지 못했습니다.');if(s.conflict)throw new Error('옮길 계좌에 같은 종목이 있습니다.');return {holdings:[]};};
const addHoldings=async(user,rows,insertOnly)=>{const s=globalThis.__pfAccountsTest;s.calls.push({user,rows,insertOnly});if(s.conflict)throw new Error('이미 보유한 종목입니다.');return [];};`);
const holdings=await import(url(code));
const id='11111111-1111-4111-8111-111111111111',target='22222222-2222-4222-8222-222222222222';
const request=(method,body,origin='http://localhost:3000')=>new Request('http://localhost:3000/api/accounts',{method,headers:{origin,host:'localhost:3000','Content-Type':'application/json'},body:JSON.stringify(body)});
const reset=()=>{state.user='owner';state.calls=[];state.missing=false;state.conflict=false;};
const row={accountId:id,broker:'증권사',account:'ISA',market:'KR',symbol:'005930',name:'삼성전자',exchange:'KOSPI',quantity:1,capturedPrice:null,averageCost:1000,capturedAt:'2026-10-09T00:00:00Z'};
test('account creation uses session ownership',async()=>{reset();assert.equal((await accounts.POST(request('POST',{broker:'증권사',name:'ISA',user:'intruder'}))).status,201);assert.equal(state.calls[0].user,'owner');});
test('account rename returns holdings and account labels together',async()=>{reset();const r=await accounts.PATCH(request('PATCH',{id,broker:'증권사',name:'연금'}));assert.equal(r.status,200);assert.ok(Array.isArray((await r.json()).holdings));assert.equal(state.calls[0].id,id);});
test('foreign or missing account rename is rejected',async()=>{reset();state.missing=true;assert.equal((await accounts.PATCH(request('PATCH',{id,broker:'증권사',name:'연금'}))).status,404);});
test('account name collisions are reported without partial updates',async()=>{reset();state.conflict=true;assert.equal((await accounts.PATCH(request('PATCH',{id,broker:'증권사',name:'ISA'}))).status,409);});
test('empty labels, invalid IDs and null payload cannot mutate accounts',async()=>{reset();for(const body of [null,{broker:' ',name:'ISA'},{broker:'증권사',name:' '},{id:'bad',broker:'증권사',name:'ISA'}])assert.equal((await accounts.PATCH(request('PATCH',body))).status,400);assert.equal(state.calls.length,0);});
test('account endpoints require authentication and same origin',async()=>{reset();state.user=null;assert.equal((await accounts.GET()).status,401);assert.equal((await accounts.POST(request('POST',{}))).status,401);reset();assert.equal((await accounts.POST(request('POST',{broker:'증권사',name:'ISA'},'https://other.example'))).status,403);assert.equal(state.calls.length,0);});
test('moving a holding uses the session owner and validated account ID',async()=>{reset();assert.equal((await holdings.PATCH(request('PATCH',{id,accountId:target}))).status,200);assert.deepEqual(state.calls[0],{user:'owner',id,accountId:target});});
test('foreign and conflicting target accounts cannot receive a holding',async()=>{reset();state.missing=true;assert.equal((await holdings.PATCH(request('PATCH',{id,accountId:target}))).status,404);reset();state.conflict=true;assert.equal((await holdings.PATCH(request('PATCH',{id,accountId:target}))).status,409);});
test('invalid account IDs cannot move or import holdings',async()=>{reset();assert.equal((await holdings.PATCH(request('PATCH',{id,accountId:'bad'}))).status,400);assert.equal((await holdings.POST(request('POST',{holdings:[{...row,accountId:'bad'}]}))).status,400);assert.equal(state.calls.length,0);});
test('direct addition rejects duplicate securities without replacing holdings',async()=>{reset();state.conflict=true;assert.equal((await holdings.POST(request('POST',{holdings:[row],insertOnly:true}))).status,409);assert.equal(state.calls[0].insertOnly,true);});
test('capture import keeps the existing replacement policy',async()=>{reset();assert.equal((await holdings.POST(request('POST',{holdings:[row]}))).status,200);assert.equal(state.calls[0].insertOnly,false);});
