import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';
import ts from 'typescript';
const state={user:'owner',calls:[]};globalThis.__pfAssignmentTest=state;
let code=ts.transpileModule(await readFile(new URL('../app/api/holdings/route.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
code=code.replace(/import \{ NextResponse \} from "next\/server";/,'const NextResponse={json:(data,options)=>Response.json(data,options)};').replace(/import \{ currentUserId \} from "[^\"]+";/,'const currentUserId=async()=>globalThis.__pfAssignmentTest.user;').replace(/import \{[^}]+\} from "[^\"]+holdings-db";/,`const addHoldings=async()=>[],listHoldings=async()=>[],removeHolding=async()=>true,updateHoldingAmounts=async()=>[],updateHoldingInstrument=async()=>[];
const updateHoldingAssignment=async(user,id,bucket,source)=>{globalThis.__pfAssignmentTest.calls.push({user,id,bucket,source});return bucket === '22222222-2222-4222-8222-222222222222' ? null : {holdings:[],snapshots:[]};};`);
const {PATCH}=await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
const id='11111111-1111-4111-8111-111111111111';
const request=(body,origin='http://localhost:3000')=>new Request('http://localhost:3000/api/holdings',{method:'PATCH',headers:{host:'localhost:3000',origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
const reset=()=>{state.user='owner';state.calls=[];};
test('direct assignment targets one authenticated holding and returns recorded snapshots',async()=>{reset();const r=await PATCH(request({id,assignmentSource:'manual',bucketId:id}));assert.equal(r.status,200);assert.deepEqual(state.calls[0],{user:'owner',id,bucket:id,source:'manual'});assert.ok(Array.isArray((await r.json()).snapshots));});
test('explicit unassigned holding is supported',async()=>{reset();assert.equal((await PATCH(request({id,assignmentSource:'manual',bucketId:null}))).status,200);});
test('automatic assignment cannot include an arbitrary direct portfolio',async()=>{reset();assert.equal((await PATCH(request({id,assignmentSource:'auto',bucketId:id}))).status,400);assert.equal(state.calls.length,0);});
test('foreign or missing portfolio is not assigned',async()=>{reset();assert.equal((await PATCH(request({id,assignmentSource:'manual',bucketId:'22222222-2222-4222-8222-222222222222'}))).status,404);});
test('unauthenticated assignment is rejected',async()=>{reset();state.user=null;assert.equal((await PATCH(request({id,assignmentSource:'manual',bucketId:null}))).status,401);});
test('cross-origin assignment is rejected',async()=>{reset();assert.equal((await PATCH(request({id,assignmentSource:'manual',bucketId:null},'https://other.example'))).status,403);});
